name: AxeOfKratos
main: notme.axeofkratos.Brain
version: 0.0.1
api-version: 1.16
author: mrbear25
description: Axe of Kratos
commands:
    pet:
        description: Teleport your pets to you
        usage: Use/<command>